### ISSUE TITLE
issue with vim and terminal

### ISSUE THREAD

**Issue by SolarAquarion** [atweiden/dotfiles#1]
whenever i leave vim using your  terminal, all the previous lines disappear and can't go back up. Like this.  
![screenshot from 2015-10-28 12-46-52](https://cloud.githubusercontent.com/assets/5307016/10795853/03756c80-7d72-11e5-985d-7a5c5fb3e112.png)

**Comment by atweiden** [comment]
Try commenting out [this line](https://github.com/atweiden/dotfiles/blob/master/_vimrc#L111)

```vim
set t_ti= t_te=
```

**Comment by SolarAquarion** [comment]
It works.  Thanks
